class Topic:
    AUDIO = 'audio'
    MAESTRO_CMD = 'maestro_cmd'
    MOTOR_SYSTEM = 'motor_system'
    NETWORK_CONNECTED = 'network_connected'
    NEW_IMAGE_COMPRESSED = 'new_image_compressed'
    NEW_IMAGE_RAW = 'new_image_raw'
    OBJECTS_DETECTED = 'objects_detected'
    SAY = 'say'
    SERVO_COMMAND = 'servo_command'
    SPEAKING = 'speaking'
    TRACKING = 'tracking'
    TRANSCRIPT = 'transcript'
    VOICE_DETECTED = 'voice_detected'
